[package]
name = "growin_core"
version = "0.1.0"
edition = "2021"

[lib]
name = "growin_core"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.23.3"
features = ["extension-module"]

[dependencies]
# Basic math
num-traits = "0.2"
